name: Check and Push

on:
    schedule:
        - cron: "0 12 * * *" # 毎日12時に実行
    workflow_dispatch: # 手動トリガー

jobs:
    check-and-push:
        runs-on: ubuntu-latest
    defaults:
        run:
            working-directory: scripts
    steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Setup Node.js
          uses: actions/setup-node@v3
          with:
              node-version: "16"
        - name: Install dependencies
          run: npm install

        - name: Run compare script
          run: node --run check

        - name: Commit and push changes
          if: success() && steps.check-and-push.should_push == 'true'
          run: |
              git config --global user.name 'github-actions[bot]'
              git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
              git add .
              git commit -m 'Automation'
              git push
